from tkinter import *
root=Tk()
frame=Frame(root)
c1=Checkbutton(frame,text="shravan")
c2=Checkbutton(frame,text="cryogen78")
c3=Checkbutton(frame,text="kamat")
l1=Label(root,text="Enter name: ")
l2=Label(root,text="Enter email: ")
l3=Label(root,text="Enter contact: ")
l4=Label(root,text="Hobbies: ")
ent1=Entry(root)
ent2=Entry(root)
ent3=Entry(root)
b=Button(root,text="submit")
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
l3.grid(row=2,column=0)
l4.grid(row=3,column=0)
ent1.grid(row=0,column=1)
ent2.grid(row=1,column=1)
ent3.grid(row=2,column=1)
c1.pack()
c2.pack()
c3.pack()
b.grid(row=5,column=0)
frame.grid(row=4,columnspan=2)
